### ISSUE TITLE
HEAD request never completes

### ISSUE THREAD

**Issue by yanns** [agourlay/cornichon#822] opened 2024-01-12 15:05 UTC
We're using the following steps:
```
          When I head("/test/<index-name>/search/products")
          Then assert status.is(200)
```

It's working fine with cornichon `0.20.8`.
It's not working anymore with cornichon `0.21.0` and `0.21.1`.

The response to the HTTP request is not observed by cornichon anymore, and the test is failing due to HTTP timeout:
```
connection timed out error after 30000 ms
```

**Comment by yanns** [comment] 2024-01-12 15:09
I've updated the ember client with the following dependency update, but it does not fix the issue:
```
"org.http4s" %% "http4s-ember-client" % "0.23.25"
```

**Comment by yanns** [comment] 2024-01-12 15:11
Hm, I guess the server sends a wrong content length:
```
curl --head localhost:7880/test/this-index-does-not-exist/search/product
HTTP/1.1 405 Method Not Allowed
Allow: GET, POST, PUT, DELETE
Server: pim-search
Date: Fri, 12 Jan 2024 15:10:30 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 66
```

**Comment by yanns** [comment] 2024-01-12 15:23
I'm trying the request with curl:
```
curl --head localhost:7880/test/this-index-does-not-exist/search/products
HTTP/1.1 404 Not Found
Server-Timing: pim-search;dur=8.43;desc="pim-search"
x-correlation-id: pim-search/c4ec431b-7493-4fc4-b17c-c60541e72332
Server: pim-search
Date: Fri, 12 Jan 2024 15:22:41 GMT
Transfer-Encoding: chunked
Content-Type: text/plain; charset=UTF-8
```

maybe `Transfer-Encoding: chunked` is an issue for the ember client?

**Comment by agourlay** [comment] 2024-01-13 07:17
Thanks for the report!

Unfortunately I was not able to reproduce the issue on my end.

I wrote a cornichon integration test sending a `HEAD` request followed by a status assertion:
- using `ember-server` for the API
- with and without `Transfer-Encoding: chunked`
- with and without body

Some ideas for the investigation:
- check that the HEAD response is actually sent on the API side (within the timeout)
- try increasing the cornichon HTTP timeout it see if maybe finishes later
- is there an actually body sent with the response? maybe try to remove it?

**Comment by yanns** [comment] 2024-01-14 13:19
I've created a small reproduction: https://github.com/yanns/reproduce-head-issue

The HTTP response I get from is a bit different from the one I get with the original application: it has a `Content-Length: 2` whereas the original one has no `Content-Length`.

Updating the cornichon version reproduces the issue.

**Comment by agourlay** [comment] 2024-01-15 08:23
Thanks for taking the time to build reproducer :+1:

However it seems the repository is private, I can't access it.

**Comment by yanns** [comment] 2024-01-15 08:30
oh good catch. I've made it public now.

**Comment by agourlay** [comment] 2024-01-16 07:57
This looks like an ember-client issue :thinking: 

If you want to move faster, I'd recommend to write a reproducer using http4s-blaze-client and http4s-ember-client directly and inform the nice http4s folks of the issue.

Otherwise I will check this myself when I can.

**Comment by yanns** [comment] 2024-01-16 09:25
Thanks for the confirmation. I'll try when I have some time.

**Comment by yanns** [comment] 2024-01-16 13:51
With the ember client, the HEAD request is successful: https://github.com/yanns/reproduce-head-issue/pull/1

**Comment by agourlay** [comment] 2024-01-16 14:25
To test a full equivalence, you need to pull the body from the response.
I think this is the place that times out.

https://github.com/agourlay/cornichon/blob/master/cornichon-core/src/main/scala/com/github/agourlay/cornichon/http/client/Http4sClient.scala#L116-L128

**Comment by yanns** [comment] 2024-01-16 14:30
You're right, I could reproduce the issue: https://github.com/yanns/reproduce-head-issue/pull/2

**Comment by yanns** [comment] 2024-01-16 14:48
issue reported on http4s: https://github.com/http4s/http4s/issues/7362

**Comment by yanns** [comment] 2024-06-03 08:11
This issue is fixed in https://github.com/http4s/http4s/releases/tag/v0.23.27

**Comment by agourlay** [comment] 2024-06-05 18:13
Fixed in https://github.com/agourlay/cornichon/releases/tag/v0.21.4

**Closed by agourlay** 2024-06-05 18:13 UTC
