### ISSUE TITLE
API request with a form-data to attach file for uploading 

### ISSUE THREAD

**Issue by InnaXITE** [agourlay/cornichon#182] opened 2018-08-20 14:48 UTC
Hi,

Would be awesome to have an ability to attach a file while calling certain endpoint.

**Comment by mibrl12** [comment] 2018-10-17 15:52
Duplicate of https://github.com/agourlay/cornichon/issues/140

**Comment by agourlay** [comment] 2024-04-07 18:32
Closing due to inactivity.

No work is planned in the foreseeable future to support this feature.

**Closed by agourlay** 2024-04-07 18:32 UTC
Labels: feature
